name: test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  shell:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - uses: actions/checkout@v4
      - run: apk add --no-cache coreutils dash jq
      - run: tests/test.sh
